### PR TITLE
Add support for is_test in submitHam and submitSpam

### LINKED ISSUE #65: submitHam and submitSpam don't send is_test property
As well as checkSpam, submitHam and submitSpam support the property is_test so you don't need to worry about make fake submits when you are testing

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #65

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
Thank you! This will go out in 3.0.0 tonight.

**Comment by sarvaje** [comment]
Perfect!!
Thank you!

**Comment by chrisfosterelli** [comment]
@sarvaje Not quite the 2 days ago I intended, but 3.0.0 just went out with this included in it. Thanks again!

**Comment by sarvaje** [comment]
Perfect!!
I will update our project :)

**Pull request merged**
